# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="ebdb-i18n-chn"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="China-specific internationaliation support for EBDB"

HOMEPAGE="https://elpa.gnu.org/packages/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/pyim
	app-emacs/ebdb"
RDEPEND="app-emacs/pyim
	app-emacs/ebdb"
