# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="so-long"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Say farewell to performance problems with minified code."

HOMEPAGE="https://elpa.gnu.org/packages/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
