# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="denote-review"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="implements review process for denote notes"

HOMEPAGE="https://codeberg.org/mattof/denote-review"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/denote"
RDEPEND="app-emacs/denote"
