# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="php-fill"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Additional fill commands for PHP code editing"

HOMEPAGE="https://github.com/arielenter/php-fill.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
