# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="llm"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Interface to pluggable llm backends"

HOMEPAGE="https://github.com/ahyatt/llm"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/plz
	app-emacs/plz-event-source
	app-emacs/plz-media-type
	app-emacs/compat"
RDEPEND="app-emacs/plz
	app-emacs/plz-event-source
	app-emacs/plz-media-type
	app-emacs/compat"
