# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="vc-jj"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="VC backend for the Jujutsu version control system"

HOMEPAGE="https://codeberg.org/emacs-jj-vc/vc-jj.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/compat"
RDEPEND="app-emacs/compat"
