# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="filechooser"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="An xdg-desktop-portal filechooser"

HOMEPAGE="https://codeberg.org/rahguzar/filechooser"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/compat"
RDEPEND="app-emacs/compat"
