# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="single"
REALNAME="company-ebdb"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="company-mode completion backend for EBDB in message-mode"

HOMEPAGE="https://elpa.gnu.org/packages/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/company
	app-emacs/ebdb"
RDEPEND="app-emacs/company
	app-emacs/ebdb"
