# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="org-gnosis"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Roam-like Knowledge Management System"

HOMEPAGE="https://thanosapollo.org/projects/org-gnosis/"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/emacsql
	app-emacs/compat"
RDEPEND="app-emacs/emacsql
	app-emacs/compat"
