# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="auth-source-xoauth2-plugin"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Authentication source plugin for xoauth2"

HOMEPAGE="https://gitlab.com/manphiz/auth-source-xoauth2-plugin"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/oauth2"
RDEPEND="app-emacs/oauth2"
