# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="mpdired"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="A dired-like client for Music Player Daemon"

HOMEPAGE="https://elpa.gnu.org/nongnu/mpdired.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
